### ISSUE TITLE
Virus notice

### ISSUE THREAD

**Issue by mamefan** [DrBeef/JKXR#6]
Both Chrome and Windows Defender say there's a virus in both or one of the JKO and JKA .exe downloads. Any reason why?

**Comment by baggyg** [comment]
This is a false positive caused by the installer we use (Inno Installer). We've done a couple of things to reduce the false positives, but its a moving field so what is fine this month maybe broken again next month. 

https://github.com/felicienfrancois/node-innosetup-compiler/issues/10
https://stackoverflow.com/questions/68834409/program-installed-with-inno-setup-seen-as-trojan-wacatac-bml

You can safely add an exception or ignore the advice it gives.
